name: example
description: "Demonstrates how to use the adp_mobile package"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  adp_mobile:
    path: ../

  adp_mobile_preview:
    git:
      url: https://github.com/Abbas1Hussein/adp_mobile_preview.git
      ref: master
      #    path: D:/flutter/packages/adp_mobile_preview


  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  custom_text: ^2.0.1
  highlight: ^0.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add all paths from HighlightPaths here:
    - lib/src/view/screens/home/tabs/icons/
    - lib/src/view/screens/home/tabs/fields/
    - lib/src/view/screens/home/tabs/layouts/
    - lib/src/view/screens/home/tabs/pickers/
    - lib/src/view/screens/home/tabs/buttons/
    - lib/src/view/screens/home/tabs/surfaces/
    - lib/src/view/screens/home/tabs/additional/
    - lib/src/view/screens/home/tabs/indicators/
    - lib/src/view/screens/home/tabs/navigation/
