name: adp_mobile
description: Implements AdaptiveUi for Android and IOS in Flutter.
version: 0.0.1
homepage: https://github.com/Abbas1Hussein/adp_mobile/#/
repository: https://github.com/Abbas1Hussein/adp_mobile
issue_tracker: https://github.com/Abbas1Hussein/adp_mobile/issues

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

topics:
  - ui
  - web
  - iOS
  - android
  - fuchsia
  - mobile
  - widgets
  - adaptive
  - responsive

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
